Feature/add coverage reports
filipesilva/angular-quickstart-lib pull request #32
Opened 2017-07-07 14:22 UTC by romulocintra

Added coverage Reports for unit tests

2017-07-08 07:23 UTC, desfero approved these changes
Thanks a lot

2017-07-12 11:07 UTC, filipesilva commented
I think this is a useful feature, but that it shouldn't be the default with running `npm test` since it increases the time it takes to run unit tests.

2017-07-13 08:52 UTC, romulocintra commented
Hi @filipesilva  agree with you , and normally on my SPA apps we have a command like  $ npm run validate that runs lint , unit test and coverage ... but in this case if we decide to go for componentization of our projects having more atomic pieces of code , the delay executing test + coverage reports is worthwhile time saving

2017-07-13 10:25 UTC, filipesilva commented
It might be worth it in your case, but that's not necessarily true for all project. What do you think of having a second karma config and a npm script to run coverage using that instead?

2017-07-13 12:08 UTC, romulocintra commented
Hi @filipesilva  , do you mean have an specific karma-coverage-config file and add an extra npm command to run coverage !? for me would be ok and yes should be most generic posible in order to fit for all projects

2017-07-13 12:11 UTC, filipesilva commented
Yeap, that is what I mean. It would be nice to be able to import and extend the other one, but I'm not sure if there's a good way of doing that.

2017-07-13 13:10 UTC, romulocintra commented
Hi @filipesilva , already made a split in Karma conf file ,  we are able to extend it for coverage features , doing a require of general configuration was the most elegant way to not duplicate to much code .

2017-07-13 13:25 UTC, filipesilva requested changes
Great job with the extension!

Could you also add `npm run coverage` to `.travis.yml`? It will test if your config works correctly and make it easier for folks to just copy the CI config.

2017-07-13 13:25 UTC, filipesilva commented on karma-coverage.conf.js
> +      require('karma-coverage'),
Some of these need to be added to `package.json`.

2017-07-14 14:36 UTC, romulocintra commented on karma-coverage.conf.js
> +      require('karma-coverage'),
already added on first PR

2017-07-14 15:52 UTC, filipesilva approved these changes

2017-07-14 15:53 UTC, merged

2017-07-14 15:53 UTC, filipesilva commented
Merging now, thanks for all the work you've done in this feature!

2017-07-16 09:59 UTC, romulocintra commented
Thanks to you all 👍